wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.14
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.13
    start_time: 1650092574
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 2
      - 19
      4: 3.8.13
      5: 0.12.14
      8:
      - 1
      - 3
      - 5
layers:
  desc: null
  value: 32
magic:
  desc: null
  value:
    enable: true
